### /hello
GET http://localhost:1198/api/hello

### generate hashed passwords
POST http://localhost:1198/api/hashed-password
Content-Type: application/json

{
    "password": "password3"
}

### login
POST http://localhost:1198/api/login
Content-Type: application/json

{
    "email": "user1@mail.com",
    "password": "password1"
}

### search
POST http://localhost:1198/api/search?title=sunday
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwiaWF0IjoxNjkzODk2MjU3LCJleHAiOjE2OTM5MDM0NTd9.MGpRZABN21FhWDnz2C4vOAay9X4jkBrdB8BkgXQ-ObE

